### ISSUE TITLE
Add Option for OpenSSL 'nameopt'

### ISSUE THREAD

**Issue by cpuwhiz22** [dsully/perl-crypt-openssl-x509#28]
Hello,

I was wondering if it would be possible to add the ability to define name options which are used with the 'nameopt' flag for OpenSSL?  I believe the default name options are being used at the moment, and they are not compliant with RFC2253.  Further, some applications require specific name formats for Issuer and subject.  It would be helpful to be able to use the name options available to OpenSSL with this module.  In the meantime I am using this module to pull all of the x509 data, but I have to use a call to the system OpenSSL binary to get the issuer since I require a particular format.

Thanks!

**Comment by filefrog** [comment]
Can you provide the workaround you are currently using, and include the OpenSSL version you have?  I may be able to get a better feel for how you intend to use nameopts that way.

In the meantime, I'm going to go read [RFC 2253](http://www.ietf.org/rfc/rfc2253.txt).

**Comment by filefrog** [comment]
Here's some documentation from OpenSSL on its `-nameopt` option:

https://www.openssl.org/docs/apps/x509.html#name_options

**Comment by cpuwhiz22** [comment]
I am currently using openssl's nameopt to get the issuer dn reversed as
well as a few other options.  If I could do this with this module it would
save me from using an object of this class, and then making a separate
system call to openssl to get a issuer string I need.  I don't have access
to my code at the moment, but if you'd like I can get the specific openssl
line I am using with the nameopts.

Essentially, the main issue is that with this module I can only get the
names for subject/issuer in one format.  This may be fine for most, but for
some applications it may need to be formatted differently and it would be
great to have the option to define that when creating the object, or
afterward even.

Let me know if you have further questions.

Thanks!
Pat

**Comment by filefrog** [comment]
I think I get it.  It seems like we can just add parameter to the as_string() function of X509::Name object, and default it to the current implicit default of 'oneline'.  I'll take a look at it and see if I can't get a pull request in to dsully.

**Comment by cpuwhiz22** [comment]
Sounds good!  Thanks for looking into this!

**Comment by filefrog** [comment]
cpuwhiz22

The more I look at this, the more I think -nameopt is better handled through `issuer_name->entries` and `subject_name->entries`, which return each component of the DN in an array, where you can (via Perl) pick out the type (CN, SN, O, etc.) and values and format them however you see fit.

OpenSSL has a ton of -nameopt formats!

Can you provide an example of what you were trying to do that required the shell-out to the openssl binary?

**Comment by cpuwhiz22** [comment]
Here is what I am presently doing:

my $reverseissuer = `openssl x509 -noout -in $temp_cert_file -issuer
-nameopt oneline,dn_rev -nameopt -space_eq \| awk -F 'issuer= ' '{print
\$2}'`;

**Comment by filefrog** [comment]
Try this:

```perl
#!/usr/bin/perl
use Crypt::OpenSSL::X509;

@ARGV or die "USAGE: $0 /path/to/cert.pem\n";
my $x509 = Crypt::OpenSSL::X509->new_from_file(@ARGV);
print join(", ", map { $_->type."=".$_->value }
                 reverse @{ $x509->issuer_name->entries }) . "\n";
```

**Comment by cpuwhiz22** [comment]
I haven't run this yet, and it looks like it will work to reverse the
issuer string, however it won't address character escaping, separators,
etc.  This may not be an issue for my use, but there may be others which
may want to be able to control the name options.  I don't know that the
effort is worth it though.  I only wanted to suggest it :-)

**Comment by filefrog** [comment]
Separators effectively exist in Perl-space now, since you can choose whatever crazy key/value, or rDN separator you want.  As for encoding, the module uses utf8, and I don't think that's likely to change.

Escaping is in similar waters.  OpenSSL (HEAD) defines the following escape disciplines:

- ASN1_STRFLGS_ESC_2253 - escapes characters per the RFC
- ASN1_STRFLGS_ESC_CTRL - escapes all control characters
- ASN1_STRFLGS_ESC_MSB - not recommended when using utf8
- ASN1_STRFLGS_ESC_QUOTE - not really an escape mode; instead of backslash-escaping problematic (but printable) code points, the whole value will be double-quoted.

I believe all of these are more adequately and properly handled by running transformations against the `$entry->value` string that is returned by the module as it stands.

The *only* place I can see where users of the module would benefit from a change is if the `$entry->type` value could be returned either in short form ('CN') or long form ('commonName').  This is probably best accomplish by a new accessor (`$entry->full_type`).

**Comment by filefrog** [comment]
Ha!  Apparently the module already supports that, via `$entry->type(1)`

**Comment by cpuwhiz22** [comment]
Nice.  Thanks for all the info!
